### ISSUE TITLE
RedDeer 2.4.0 Release work under SimRel 2018-12

### ISSUE THREAD

**Issue by odockal** [eclipse/reddeer#1963]
This issue is a form of an epic task consisting of all steps that are required to undertake in order to release RedDeer final bits under Eclipse Simultaneous Release 2018-12. 

Eclipse Project plan 2018-12 [link].

M1 | 2018-10-12 | 4.10 M1
-- | -- | --
M2 | 2018-11-02 | 4.10 M2 (only submit I-build)
M3 | 2018-11-23 | 4.10 M3
  | 2018-11-28 | IP Log Submission Deadline
RC1 | 2018-11-30 | 4.10 RC1
  | 2018-12-05 | Review Material Submission Deadline
RC2 | 2018-12-07 | 4.10 RC2

- [x] Upversion to proper snapshot version (2.4.0-SNAPSHOT) if not done yet
 * mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=2.3.0.qualifier
* In addition, these files were modified manually:
* archetype/src/main/resources/archetype-resources/pom.xml
* archetype/pom.xml
- [x] share the intent to participate in SimRel (should be done at latest at M1, should be valid for one year until June release 2019) 
- [x] Create new project release 
* https://projects.eclipse.org/projects/technology.reddeer -> Commiter Tools -> Create a new Release
* - [x] Create a milestone(s) in release plan
* - [x] Schedule Release Review after project release is created (1st of 3rd Wed. on each month)
* - [x] This review is pending; contact The Eclipse Management Organization (emo@eclipse.org) to make it public. (can be found under https://projects.eclipse.org/projects/technology.reddeer/releases/2.4.0 -> Review: -> 2.4.0 Release Review link)
* - [x] Request for PMC approval (Committer Tools › Communication › Send Email to the PMC)
* - [x] get +1 on technology-pmc mailing list request
* - [x] Create IP Log - https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18000
* - [x] Wait for release review is done on planned date after all above steps are fulfilled
* - [x] Bugzilla for release review with approvals: https://bugs.eclipse.org/bugs/show_bug.cgi?id=540144

- [x] Jump in SimRel Milestone release with offset +3
this is probably M2 +3 as reddeer cannot be built unless we got full stack of packages in some update site and this is usually happening at the end of M1.
- [x] RedDeer milestone releasing - MX, RCX, Final, includes:
* Implement changes, fixes, etc. to RD
* Release proper milestone via https://ci.eclipse.org/reddeer CCI
* Create Eclipse SimRel aggregation build repo gerrit commit, validate - https://ci.eclipse.org/simrel/job/simrel.photon.runaggregator.VALIDATE.gerrit/, push, see sub-tasks.

- [x] Spread release note to proper mailing lists (reddeer-dev)

**SubTasks:**

Creating gerrit commit to Eclipse Simrel aggregation build repo
* requires signed ECA, and Eclipse user account
* Resources: https://wiki.eclipse.org/Simrel/Contributing_to_Simrel_Aggregation_Build, 
 https://wiki.eclipse.org/Gerrit
* Git repo address: git clone https://git.eclipse.org/r/simrel/org.eclipse.simrel.build
* Add repo locally into IDE via Git perspective
* Open simrel repo properties - Configuration -> setup those branch.master.remote=origin, branch.master.merge=refs/heads/master and branch.master.rebase=true
* (Optional) Install the CBI p2Repo Aggregator - http://download.eclipse.org/cbi/updates/aggregator/ide/4.8 
* make changes to particular aggrcon file (reddeer.aggrcon)
* Test build locally: Aggregation (only) from Eclipse IDE and CBI aggregator
From the aggregation editor, right-click on the aggregation model and run Clean then Build Aggregation. See CBI/aggregator/manual#Global_actions OR in the repo cli, run mvn clean verify
* Stage changes, create commit message with change ID attached (signoff as well)
* Commit and push...
* When pushing commit into gerrit repo over HTTPS, use passphrase that can be get while being logged here: https://git.eclipse.org/r/#/settings/http-password
* Gerrit commit created, validation jenkins job started: https://ci.eclipse.org/simrel/job/simrel.photon.runaggregator.VALIDATE.gerrit/
* If all good, job will add +1 to the gerrit commit, one needs to get another +2 from someone who has right to push into repo
* push to repo

[link]: https://www.eclipse.org/projects/project-plan.php?planurl=http://www.eclipse.org/eclipse/development/plans/eclipse_project_plan_4_10.xml

**Comment by odockal** [comment]
- [x] Jump in SimRel Milestone release with offset +3
* this is probably M2 +3 as reddeer cannot be built unless we got full stack of packages in some update site and this is usually happening at the end of M1.
- [x] RD M2 released and pushed to simrel aggreagate file, see gerrit commit: https://git.eclipse.org/r/#/c/132087/
* Simrel run aggregator pipeline job for gerrit changes is green: https://ci.eclipse.org/simrel/job/simrel.runaggregator.pipeline/
- [x] RD RC1/Final bits are tagged and released - https://download.eclipse.org/reddeer/releases/2.4.0/, https://ci.eclipse.org/reddeer/job/reddeer.release/7/, We used 2.4.0.RC1 tag for final build/bits as there were no changes
* Change is made into simrel aggregation repo for 2018-12 RC2 (gerrit: https://git.eclipse.org/r/#/c/133930/, aggregator pipeline job is green)

**Comment by odockal** [comment]
@jkopriva Seems like we can close this issue as we released without issue (so far) and eclipse is out, release notes were sent. Thank you for your good work!
