### ISSUE TITLE
RedDeer 2.5.0 Release work under SimRel 2019-03

### ISSUE THREAD

**Issue by odockal** [eclipse/reddeer#1981]
This issue is a form of an epic task consisting of all steps that are required to undertake in order to release RedDeer final bits under Eclipse Simultaneous Release 2019-03. 

Eclipse Project plan 2019-03 [link].

Release | Date | Span | Notes
-- | -- | -- | --
2019-03 M1 | Friday, January 18, 2019 | 01/11 to 01/18 | 3 weeks from 2018-12 GA
2019-03 M2 | Friday, February 8, 2019 | 02/01 to 02/08 | 3 weeks from M1
2019-03 M3 | Friday, March 1, 2019 | 02/22 to 03/01 | 3 weeks from M2
2019-03 RC1 | Friday, March 8, 2019 | 03/01 to 03/08 | 1 week from M3
2019-03 RC2 | Friday, March 15, 2019 | 03/08 to 03/15 | 1 week from RC1
Quiet week | 03/15 to 03/19 | No builds during "quiet period". It is assumed all code is done by the end of RC2.
2019-03 GA | Wednesday, March 20, 2019 |   | 5 days from RC2

- [x] Plan work for new release: [issues]
- [x] Upversion to proper snapshot version (2.5.0-SNAPSHOT) if not done yet
 * mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=2.3.0.qualifier
* In addition, these files were modified manually:
* archetype/src/main/resources/archetype-resources/pom.xml
* archetype/pom.xml
- [x] share the intent to participate in SimRel (should be done at latest at M1, should be valid for one year until June release 2019) 
- [x] Create new project release 
* https://projects.eclipse.org/projects/technology.reddeer -> Commiter Tools -> Create a new Release
* - [x] Create a milestone(s) in release plan
* - [x] Schedule Release Review after project release is created (1st of 3rd Wed. on each month)
* - [x] This review is pending; contact The Eclipse Management Organization (emo@eclipse.org) to make it public. (can be found under https://projects.eclipse.org/projects/technology.reddeer/releases/2.5.0 -> Review: -> 2.5.0 Release Review link)
* - [x] Request for PMC approval (Committer Tools › Communication › Send Email to the PMC)
* - [x] Get +1 on technology-pmc mailing list request
* - [x] Create IP Log - https://dev.eclipse.org/ipzilla
* - [x] Wait for release review is done on planned date after all above steps are fulfilled
* - [x] Bugzilla for release review with approvals: https://bugs.eclipse.org/bugs/show_bug.cgi?id=544040

- [x] Jump in SimRel Milestone release with offset +3
this is probably M2 +3 as reddeer cannot be built unless we got full stack of packages in some update site and this is usually happening at the end of M1.
- [ ] RedDeer milestone releasing - MX, RCX, Final, includes:
* Implement changes, fixes, etc. to RD
* Release proper milestone via https://ci.eclipse.org/reddeer CCI
* Create Eclipse SimRel aggregation build repo gerrit commit, validate - https://ci.eclipse.org/simrel/job/simrel.photon.runaggregator.VALIDATE.gerrit/, push, see sub-tasks.

- [x] Spread release note to proper mailing lists (reddeer-dev)
- [x] Create new release tag and upload artifacts using github-project-automation scripts from 
- [x] Triage issues for next release, close, move, etc.

**SubTasks:**

Creating gerrit commit to Eclipse Simrel aggregation build repo
* requires signed ECA, and Eclipse user account
* Resources: https://wiki.eclipse.org/Simrel/Contributing_to_Simrel_Aggregation_Build, 
 https://wiki.eclipse.org/Gerrit
* Git repo address: git clone https://git.eclipse.org/r/simrel/org.eclipse.simrel.build
* Add repo locally into IDE via Git perspective
* Open simrel repo properties - Configuration -> setup those branch.master.remote=origin, branch.master.merge=refs/heads/master and branch.master.rebase=true
* (Optional) Install the CBI p2Repo Aggregator - http://download.eclipse.org/cbi/updates/aggregator/ide/4.8 
* make changes to particular aggrcon file (reddeer.aggrcon)
* Test build locally: Aggregation (only) from Eclipse IDE and CBI aggregator
From the aggregation editor, right-click on the aggregation model and run Clean then Build Aggregation. See CBI/aggregator/manual#Global_actions OR in the repo cli, run mvn clean verify
* Stage changes, create commit message with change ID attached (signoff as well)
* Commit and push...
* When pushing commit into gerrit repo over HTTPS, use passphrase that can be get while being logged here: https://git.eclipse.org/r/#/settings/http-password
* Gerrit commit created, validation jenkins job started: https://ci.eclipse.org/simrel/job/simrel.photon.runaggregator.VALIDATE.gerrit/
* If all good, job will add +1 to the gerrit commit, one needs to get another +2 from someone who has right to push into repo
* push to repo

Create and push github tag
* Create an annotated (ideally) tag aiming proper Eclipse Milestone where RedDeer milestone bits will be included
* `git tag -a <tagname>`
* write a brief description
* check tag's head commit `git show <tagname>`
* push tag into origin `git push --tags`
* push tag into upstream `git push upstream --tags`

Creating a milestone
* Run https://ci.eclipse.org/reddeer/job/reddeer.milestone/ and set REDDEER_TAG to `<tagname>`
* Pass empty string into BUILD_ALIAS as we stopped using build aliases
* Create a gerrit commit on org.eclipse.simrel.build repo, see another subtask

[link]: https://wiki.eclipse.org/SimRel/2019-03/Simultaneous_Release_Plan
[issues]: https://github.com/eclipse/reddeer/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.5.0
[planurl]=http://www.eclipse.org/eclipse/development/plans/eclipse_project_plan_4_11.xml
